//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseManager.ServiceReference2 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AnalogInput", Namespace="http://schemas.datacontract.org/2004/07/SCADACore")]
    [System.SerializableAttribute()]
    public partial class AnalogInput : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double AnalogValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double HighLimitField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IOAdressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double LowLimitField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ONOFF_scanField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double ScanTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TagNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UnitsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double AnalogValue {
            get {
                return this.AnalogValueField;
            }
            set {
                if ((this.AnalogValueField.Equals(value) != true)) {
                    this.AnalogValueField = value;
                    this.RaisePropertyChanged("AnalogValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double HighLimit {
            get {
                return this.HighLimitField;
            }
            set {
                if ((this.HighLimitField.Equals(value) != true)) {
                    this.HighLimitField = value;
                    this.RaisePropertyChanged("HighLimit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IOAdress {
            get {
                return this.IOAdressField;
            }
            set {
                if ((object.ReferenceEquals(this.IOAdressField, value) != true)) {
                    this.IOAdressField = value;
                    this.RaisePropertyChanged("IOAdress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double LowLimit {
            get {
                return this.LowLimitField;
            }
            set {
                if ((this.LowLimitField.Equals(value) != true)) {
                    this.LowLimitField = value;
                    this.RaisePropertyChanged("LowLimit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool ONOFF_scan {
            get {
                return this.ONOFF_scanField;
            }
            set {
                if ((this.ONOFF_scanField.Equals(value) != true)) {
                    this.ONOFF_scanField = value;
                    this.RaisePropertyChanged("ONOFF_scan");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double ScanTime {
            get {
                return this.ScanTimeField;
            }
            set {
                if ((this.ScanTimeField.Equals(value) != true)) {
                    this.ScanTimeField = value;
                    this.RaisePropertyChanged("ScanTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TagName {
            get {
                return this.TagNameField;
            }
            set {
                if ((object.ReferenceEquals(this.TagNameField, value) != true)) {
                    this.TagNameField = value;
                    this.RaisePropertyChanged("TagName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Units {
            get {
                return this.UnitsField;
            }
            set {
                if ((object.ReferenceEquals(this.UnitsField, value) != true)) {
                    this.UnitsField = value;
                    this.RaisePropertyChanged("Units");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AnalogOutput", Namespace="http://schemas.datacontract.org/2004/07/SCADACore")]
    [System.SerializableAttribute()]
    public partial class AnalogOutput : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double HighLimitField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IOAdressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double InitialValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double LowLimitField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TagNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double HighLimit {
            get {
                return this.HighLimitField;
            }
            set {
                if ((this.HighLimitField.Equals(value) != true)) {
                    this.HighLimitField = value;
                    this.RaisePropertyChanged("HighLimit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IOAdress {
            get {
                return this.IOAdressField;
            }
            set {
                if ((object.ReferenceEquals(this.IOAdressField, value) != true)) {
                    this.IOAdressField = value;
                    this.RaisePropertyChanged("IOAdress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double InitialValue {
            get {
                return this.InitialValueField;
            }
            set {
                if ((this.InitialValueField.Equals(value) != true)) {
                    this.InitialValueField = value;
                    this.RaisePropertyChanged("InitialValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double LowLimit {
            get {
                return this.LowLimitField;
            }
            set {
                if ((this.LowLimitField.Equals(value) != true)) {
                    this.LowLimitField = value;
                    this.RaisePropertyChanged("LowLimit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TagName {
            get {
                return this.TagNameField;
            }
            set {
                if ((object.ReferenceEquals(this.TagNameField, value) != true)) {
                    this.TagNameField = value;
                    this.RaisePropertyChanged("TagName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DigitalInput", Namespace="http://schemas.datacontract.org/2004/07/SCADACore")]
    [System.SerializableAttribute()]
    public partial class DigitalInput : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IOAdressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ONOFF_scanField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double ScanTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TagNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double digitalValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IOAdress {
            get {
                return this.IOAdressField;
            }
            set {
                if ((object.ReferenceEquals(this.IOAdressField, value) != true)) {
                    this.IOAdressField = value;
                    this.RaisePropertyChanged("IOAdress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool ONOFF_scan {
            get {
                return this.ONOFF_scanField;
            }
            set {
                if ((this.ONOFF_scanField.Equals(value) != true)) {
                    this.ONOFF_scanField = value;
                    this.RaisePropertyChanged("ONOFF_scan");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double ScanTime {
            get {
                return this.ScanTimeField;
            }
            set {
                if ((this.ScanTimeField.Equals(value) != true)) {
                    this.ScanTimeField = value;
                    this.RaisePropertyChanged("ScanTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TagName {
            get {
                return this.TagNameField;
            }
            set {
                if ((object.ReferenceEquals(this.TagNameField, value) != true)) {
                    this.TagNameField = value;
                    this.RaisePropertyChanged("TagName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double digitalValue {
            get {
                return this.digitalValueField;
            }
            set {
                if ((this.digitalValueField.Equals(value) != true)) {
                    this.digitalValueField = value;
                    this.RaisePropertyChanged("digitalValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DigitalOutput", Namespace="http://schemas.datacontract.org/2004/07/SCADACore")]
    [System.SerializableAttribute()]
    public partial class DigitalOutput : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IO_AdressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string descriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double initial_ValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string tag_nameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IO_Adress {
            get {
                return this.IO_AdressField;
            }
            set {
                if ((object.ReferenceEquals(this.IO_AdressField, value) != true)) {
                    this.IO_AdressField = value;
                    this.RaisePropertyChanged("IO_Adress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.descriptionField, value) != true)) {
                    this.descriptionField = value;
                    this.RaisePropertyChanged("description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double initial_Value {
            get {
                return this.initial_ValueField;
            }
            set {
                if ((this.initial_ValueField.Equals(value) != true)) {
                    this.initial_ValueField = value;
                    this.RaisePropertyChanged("initial_Value");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string tag_name {
            get {
                return this.tag_nameField;
            }
            set {
                if ((object.ReferenceEquals(this.tag_nameField, value) != true)) {
                    this.tag_nameField = value;
                    this.RaisePropertyChanged("tag_name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference2.IAuthentication")]
    public interface IAuthentication {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthentication/Registration", ReplyAction="http://tempuri.org/IAuthentication/RegistrationResponse")]
        string Registration(string name, string surname, string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthentication/Registration", ReplyAction="http://tempuri.org/IAuthentication/RegistrationResponse")]
        System.Threading.Tasks.Task<string> RegistrationAsync(string name, string surname, string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthentication/DeleteProfile", ReplyAction="http://tempuri.org/IAuthentication/DeleteProfileResponse")]
        bool DeleteProfile(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthentication/DeleteProfile", ReplyAction="http://tempuri.org/IAuthentication/DeleteProfileResponse")]
        System.Threading.Tasks.Task<bool> DeleteProfileAsync(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthentication/Login", ReplyAction="http://tempuri.org/IAuthentication/LoginResponse")]
        string Login(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthentication/Login", ReplyAction="http://tempuri.org/IAuthentication/LoginResponse")]
        System.Threading.Tasks.Task<string> LoginAsync(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthentication/ChangePassword", ReplyAction="http://tempuri.org/IAuthentication/ChangePasswordResponse")]
        string ChangePassword(string username, string password, string update_password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthentication/ChangePassword", ReplyAction="http://tempuri.org/IAuthentication/ChangePasswordResponse")]
        System.Threading.Tasks.Task<string> ChangePasswordAsync(string username, string password, string update_password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthentication/Logout", ReplyAction="http://tempuri.org/IAuthentication/LogoutResponse")]
        bool Logout(string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthentication/Logout", ReplyAction="http://tempuri.org/IAuthentication/LogoutResponse")]
        System.Threading.Tasks.Task<bool> LogoutAsync(string token);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAuthenticationChannel : DatabaseManager.ServiceReference2.IAuthentication, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AuthenticationClient : System.ServiceModel.ClientBase<DatabaseManager.ServiceReference2.IAuthentication>, DatabaseManager.ServiceReference2.IAuthentication {
        
        public AuthenticationClient() {
        }
        
        public AuthenticationClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AuthenticationClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AuthenticationClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AuthenticationClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string Registration(string name, string surname, string username, string password) {
            return base.Channel.Registration(name, surname, username, password);
        }
        
        public System.Threading.Tasks.Task<string> RegistrationAsync(string name, string surname, string username, string password) {
            return base.Channel.RegistrationAsync(name, surname, username, password);
        }
        
        public bool DeleteProfile(string username, string password) {
            return base.Channel.DeleteProfile(username, password);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteProfileAsync(string username, string password) {
            return base.Channel.DeleteProfileAsync(username, password);
        }
        
        public string Login(string username, string password) {
            return base.Channel.Login(username, password);
        }
        
        public System.Threading.Tasks.Task<string> LoginAsync(string username, string password) {
            return base.Channel.LoginAsync(username, password);
        }
        
        public string ChangePassword(string username, string password, string update_password) {
            return base.Channel.ChangePassword(username, password, update_password);
        }
        
        public System.Threading.Tasks.Task<string> ChangePasswordAsync(string username, string password, string update_password) {
            return base.Channel.ChangePasswordAsync(username, password, update_password);
        }
        
        public bool Logout(string token) {
            return base.Channel.Logout(token);
        }
        
        public System.Threading.Tasks.Task<bool> LogoutAsync(string token) {
            return base.Channel.LogoutAsync(token);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference2.IDatabaseManager")]
    public interface IDatabaseManager {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDatabaseManager/AddAI", ReplyAction="http://tempuri.org/IDatabaseManager/AddAIResponse")]
        void AddAI(DatabaseManager.ServiceReference2.AnalogInput AI);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDatabaseManager/AddAI", ReplyAction="http://tempuri.org/IDatabaseManager/AddAIResponse")]
        System.Threading.Tasks.Task AddAIAsync(DatabaseManager.ServiceReference2.AnalogInput AI);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDatabaseManager/AddAO", ReplyAction="http://tempuri.org/IDatabaseManager/AddAOResponse")]
        void AddAO(DatabaseManager.ServiceReference2.AnalogOutput AO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDatabaseManager/AddAO", ReplyAction="http://tempuri.org/IDatabaseManager/AddAOResponse")]
        System.Threading.Tasks.Task AddAOAsync(DatabaseManager.ServiceReference2.AnalogOutput AO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDatabaseManager/AddDI", ReplyAction="http://tempuri.org/IDatabaseManager/AddDIResponse")]
        void AddDI(DatabaseManager.ServiceReference2.DigitalInput DI);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDatabaseManager/AddDI", ReplyAction="http://tempuri.org/IDatabaseManager/AddDIResponse")]
        System.Threading.Tasks.Task AddDIAsync(DatabaseManager.ServiceReference2.DigitalInput DI);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDatabaseManager/AddDO", ReplyAction="http://tempuri.org/IDatabaseManager/AddDOResponse")]
        void AddDO(DatabaseManager.ServiceReference2.DigitalOutput DO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDatabaseManager/AddDO", ReplyAction="http://tempuri.org/IDatabaseManager/AddDOResponse")]
        System.Threading.Tasks.Task AddDOAsync(DatabaseManager.ServiceReference2.DigitalOutput DO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDatabaseManager/removeDO", ReplyAction="http://tempuri.org/IDatabaseManager/removeDOResponse")]
        void removeDO(DatabaseManager.ServiceReference2.DigitalOutput DO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDatabaseManager/removeDO", ReplyAction="http://tempuri.org/IDatabaseManager/removeDOResponse")]
        System.Threading.Tasks.Task removeDOAsync(DatabaseManager.ServiceReference2.DigitalOutput DO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDatabaseManager/removeAO", ReplyAction="http://tempuri.org/IDatabaseManager/removeAOResponse")]
        void removeAO(DatabaseManager.ServiceReference2.AnalogOutput AO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDatabaseManager/removeAO", ReplyAction="http://tempuri.org/IDatabaseManager/removeAOResponse")]
        System.Threading.Tasks.Task removeAOAsync(DatabaseManager.ServiceReference2.AnalogOutput AO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDatabaseManager/removeAI", ReplyAction="http://tempuri.org/IDatabaseManager/removeAIResponse")]
        void removeAI(DatabaseManager.ServiceReference2.AnalogInput AI);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDatabaseManager/removeAI", ReplyAction="http://tempuri.org/IDatabaseManager/removeAIResponse")]
        System.Threading.Tasks.Task removeAIAsync(DatabaseManager.ServiceReference2.AnalogInput AI);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDatabaseManager/removeDI", ReplyAction="http://tempuri.org/IDatabaseManager/removeDIResponse")]
        void removeDI(DatabaseManager.ServiceReference2.DigitalInput DI);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDatabaseManager/removeDI", ReplyAction="http://tempuri.org/IDatabaseManager/removeDIResponse")]
        System.Threading.Tasks.Task removeDIAsync(DatabaseManager.ServiceReference2.DigitalInput DI);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDatabaseManager/LoadDataToGridAO", ReplyAction="http://tempuri.org/IDatabaseManager/LoadDataToGridAOResponse")]
        DatabaseManager.ServiceReference2.AnalogOutput[] LoadDataToGridAO();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDatabaseManager/LoadDataToGridAO", ReplyAction="http://tempuri.org/IDatabaseManager/LoadDataToGridAOResponse")]
        System.Threading.Tasks.Task<DatabaseManager.ServiceReference2.AnalogOutput[]> LoadDataToGridAOAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDatabaseManager/LoadDataToGrid", ReplyAction="http://tempuri.org/IDatabaseManager/LoadDataToGridResponse")]
        DatabaseManager.ServiceReference2.DigitalOutput[] LoadDataToGrid();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDatabaseManager/LoadDataToGrid", ReplyAction="http://tempuri.org/IDatabaseManager/LoadDataToGridResponse")]
        System.Threading.Tasks.Task<DatabaseManager.ServiceReference2.DigitalOutput[]> LoadDataToGridAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDatabaseManager/LoadDataToGridAI", ReplyAction="http://tempuri.org/IDatabaseManager/LoadDataToGridAIResponse")]
        DatabaseManager.ServiceReference2.AnalogInput[] LoadDataToGridAI();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDatabaseManager/LoadDataToGridAI", ReplyAction="http://tempuri.org/IDatabaseManager/LoadDataToGridAIResponse")]
        System.Threading.Tasks.Task<DatabaseManager.ServiceReference2.AnalogInput[]> LoadDataToGridAIAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDatabaseManager/LoadDataToGridDI", ReplyAction="http://tempuri.org/IDatabaseManager/LoadDataToGridDIResponse")]
        DatabaseManager.ServiceReference2.DigitalInput[] LoadDataToGridDI();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDatabaseManager/LoadDataToGridDI", ReplyAction="http://tempuri.org/IDatabaseManager/LoadDataToGridDIResponse")]
        System.Threading.Tasks.Task<DatabaseManager.ServiceReference2.DigitalInput[]> LoadDataToGridDIAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDatabaseManager/SaveChanges", ReplyAction="http://tempuri.org/IDatabaseManager/SaveChangesResponse")]
        void SaveChanges(DatabaseManager.ServiceReference2.AnalogOutput AO, double change);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDatabaseManager/SaveChanges", ReplyAction="http://tempuri.org/IDatabaseManager/SaveChangesResponse")]
        System.Threading.Tasks.Task SaveChangesAsync(DatabaseManager.ServiceReference2.AnalogOutput AO, double change);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDatabaseManager/SaveChangesDO", ReplyAction="http://tempuri.org/IDatabaseManager/SaveChangesDOResponse")]
        void SaveChangesDO(DatabaseManager.ServiceReference2.DigitalOutput DO, double change);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDatabaseManager/SaveChangesDO", ReplyAction="http://tempuri.org/IDatabaseManager/SaveChangesDOResponse")]
        System.Threading.Tasks.Task SaveChangesDOAsync(DatabaseManager.ServiceReference2.DigitalOutput DO, double change);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDatabaseManager/SaveChangesAI", ReplyAction="http://tempuri.org/IDatabaseManager/SaveChangesAIResponse")]
        void SaveChangesAI(DatabaseManager.ServiceReference2.AnalogInput AI, bool change);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDatabaseManager/SaveChangesAI", ReplyAction="http://tempuri.org/IDatabaseManager/SaveChangesAIResponse")]
        System.Threading.Tasks.Task SaveChangesAIAsync(DatabaseManager.ServiceReference2.AnalogInput AI, bool change);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDatabaseManager/SaveChangesDI", ReplyAction="http://tempuri.org/IDatabaseManager/SaveChangesDIResponse")]
        void SaveChangesDI(DatabaseManager.ServiceReference2.DigitalInput DI, bool change);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDatabaseManager/SaveChangesDI", ReplyAction="http://tempuri.org/IDatabaseManager/SaveChangesDIResponse")]
        System.Threading.Tasks.Task SaveChangesDIAsync(DatabaseManager.ServiceReference2.DigitalInput DI, bool change);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDatabaseManager/Simulation", ReplyAction="http://tempuri.org/IDatabaseManager/SimulationResponse")]
        void Simulation(DatabaseManager.ServiceReference2.DigitalInput DI);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDatabaseManager/Simulation", ReplyAction="http://tempuri.org/IDatabaseManager/SimulationResponse")]
        System.Threading.Tasks.Task SimulationAsync(DatabaseManager.ServiceReference2.DigitalInput DI);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDatabaseManager/Simulation1", ReplyAction="http://tempuri.org/IDatabaseManager/Simulation1Response")]
        void Simulation1(DatabaseManager.ServiceReference2.AnalogInput AI);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDatabaseManager/Simulation1", ReplyAction="http://tempuri.org/IDatabaseManager/Simulation1Response")]
        System.Threading.Tasks.Task Simulation1Async(DatabaseManager.ServiceReference2.AnalogInput AI);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDatabaseManager/LoadThreadDi", ReplyAction="http://tempuri.org/IDatabaseManager/LoadThreadDiResponse")]
        void LoadThreadDi();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDatabaseManager/LoadThreadDi", ReplyAction="http://tempuri.org/IDatabaseManager/LoadThreadDiResponse")]
        System.Threading.Tasks.Task LoadThreadDiAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDatabaseManager/LoadThreadAi", ReplyAction="http://tempuri.org/IDatabaseManager/LoadThreadAiResponse")]
        void LoadThreadAi();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDatabaseManager/LoadThreadAi", ReplyAction="http://tempuri.org/IDatabaseManager/LoadThreadAiResponse")]
        System.Threading.Tasks.Task LoadThreadAiAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDatabaseManager/startPLC", ReplyAction="http://tempuri.org/IDatabaseManager/startPLCResponse")]
        void startPLC();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDatabaseManager/startPLC", ReplyAction="http://tempuri.org/IDatabaseManager/startPLCResponse")]
        System.Threading.Tasks.Task startPLCAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDatabaseManager/loadAdressAI", ReplyAction="http://tempuri.org/IDatabaseManager/loadAdressAIResponse")]
        System.Collections.Generic.Dictionary<string, bool> loadAdressAI(System.Collections.Generic.Dictionary<string, bool> AI);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDatabaseManager/loadAdressAI", ReplyAction="http://tempuri.org/IDatabaseManager/loadAdressAIResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<string, bool>> loadAdressAIAsync(System.Collections.Generic.Dictionary<string, bool> AI);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDatabaseManager/loadAdressDI", ReplyAction="http://tempuri.org/IDatabaseManager/loadAdressDIResponse")]
        System.Collections.Generic.Dictionary<string, bool> loadAdressDI(System.Collections.Generic.Dictionary<string, bool> DI);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDatabaseManager/loadAdressDI", ReplyAction="http://tempuri.org/IDatabaseManager/loadAdressDIResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<string, bool>> loadAdressDIAsync(System.Collections.Generic.Dictionary<string, bool> DI);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDatabaseManager/loadAdressAO", ReplyAction="http://tempuri.org/IDatabaseManager/loadAdressAOResponse")]
        System.Collections.Generic.Dictionary<string, bool> loadAdressAO(System.Collections.Generic.Dictionary<string, bool> AO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDatabaseManager/loadAdressAO", ReplyAction="http://tempuri.org/IDatabaseManager/loadAdressAOResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<string, bool>> loadAdressAOAsync(System.Collections.Generic.Dictionary<string, bool> AO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDatabaseManager/loadAdressDO", ReplyAction="http://tempuri.org/IDatabaseManager/loadAdressDOResponse")]
        System.Collections.Generic.Dictionary<string, bool> loadAdressDO(System.Collections.Generic.Dictionary<string, bool> DO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDatabaseManager/loadAdressDO", ReplyAction="http://tempuri.org/IDatabaseManager/loadAdressDOResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<string, bool>> loadAdressDOAsync(System.Collections.Generic.Dictionary<string, bool> DO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDatabaseManager/clearData", ReplyAction="http://tempuri.org/IDatabaseManager/clearDataResponse")]
        void clearData();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDatabaseManager/clearData", ReplyAction="http://tempuri.org/IDatabaseManager/clearDataResponse")]
        System.Threading.Tasks.Task clearDataAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDatabaseManager/WriteXML", ReplyAction="http://tempuri.org/IDatabaseManager/WriteXMLResponse")]
        void WriteXML();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDatabaseManager/WriteXML", ReplyAction="http://tempuri.org/IDatabaseManager/WriteXMLResponse")]
        System.Threading.Tasks.Task WriteXMLAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDatabaseManager/ReadXML", ReplyAction="http://tempuri.org/IDatabaseManager/ReadXMLResponse")]
        void ReadXML();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDatabaseManager/ReadXML", ReplyAction="http://tempuri.org/IDatabaseManager/ReadXMLResponse")]
        System.Threading.Tasks.Task ReadXMLAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDatabaseManagerChannel : DatabaseManager.ServiceReference2.IDatabaseManager, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DatabaseManagerClient : System.ServiceModel.ClientBase<DatabaseManager.ServiceReference2.IDatabaseManager>, DatabaseManager.ServiceReference2.IDatabaseManager {
        
        public DatabaseManagerClient() {
        }
        
        public DatabaseManagerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DatabaseManagerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DatabaseManagerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DatabaseManagerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void AddAI(DatabaseManager.ServiceReference2.AnalogInput AI) {
            base.Channel.AddAI(AI);
        }
        
        public System.Threading.Tasks.Task AddAIAsync(DatabaseManager.ServiceReference2.AnalogInput AI) {
            return base.Channel.AddAIAsync(AI);
        }
        
        public void AddAO(DatabaseManager.ServiceReference2.AnalogOutput AO) {
            base.Channel.AddAO(AO);
        }
        
        public System.Threading.Tasks.Task AddAOAsync(DatabaseManager.ServiceReference2.AnalogOutput AO) {
            return base.Channel.AddAOAsync(AO);
        }
        
        public void AddDI(DatabaseManager.ServiceReference2.DigitalInput DI) {
            base.Channel.AddDI(DI);
        }
        
        public System.Threading.Tasks.Task AddDIAsync(DatabaseManager.ServiceReference2.DigitalInput DI) {
            return base.Channel.AddDIAsync(DI);
        }
        
        public void AddDO(DatabaseManager.ServiceReference2.DigitalOutput DO) {
            base.Channel.AddDO(DO);
        }
        
        public System.Threading.Tasks.Task AddDOAsync(DatabaseManager.ServiceReference2.DigitalOutput DO) {
            return base.Channel.AddDOAsync(DO);
        }
        
        public void removeDO(DatabaseManager.ServiceReference2.DigitalOutput DO) {
            base.Channel.removeDO(DO);
        }
        
        public System.Threading.Tasks.Task removeDOAsync(DatabaseManager.ServiceReference2.DigitalOutput DO) {
            return base.Channel.removeDOAsync(DO);
        }
        
        public void removeAO(DatabaseManager.ServiceReference2.AnalogOutput AO) {
            base.Channel.removeAO(AO);
        }
        
        public System.Threading.Tasks.Task removeAOAsync(DatabaseManager.ServiceReference2.AnalogOutput AO) {
            return base.Channel.removeAOAsync(AO);
        }
        
        public void removeAI(DatabaseManager.ServiceReference2.AnalogInput AI) {
            base.Channel.removeAI(AI);
        }
        
        public System.Threading.Tasks.Task removeAIAsync(DatabaseManager.ServiceReference2.AnalogInput AI) {
            return base.Channel.removeAIAsync(AI);
        }
        
        public void removeDI(DatabaseManager.ServiceReference2.DigitalInput DI) {
            base.Channel.removeDI(DI);
        }
        
        public System.Threading.Tasks.Task removeDIAsync(DatabaseManager.ServiceReference2.DigitalInput DI) {
            return base.Channel.removeDIAsync(DI);
        }
        
        public DatabaseManager.ServiceReference2.AnalogOutput[] LoadDataToGridAO() {
            return base.Channel.LoadDataToGridAO();
        }
        
        public System.Threading.Tasks.Task<DatabaseManager.ServiceReference2.AnalogOutput[]> LoadDataToGridAOAsync() {
            return base.Channel.LoadDataToGridAOAsync();
        }
        
        public DatabaseManager.ServiceReference2.DigitalOutput[] LoadDataToGrid() {
            return base.Channel.LoadDataToGrid();
        }
        
        public System.Threading.Tasks.Task<DatabaseManager.ServiceReference2.DigitalOutput[]> LoadDataToGridAsync() {
            return base.Channel.LoadDataToGridAsync();
        }
        
        public DatabaseManager.ServiceReference2.AnalogInput[] LoadDataToGridAI() {
            return base.Channel.LoadDataToGridAI();
        }
        
        public System.Threading.Tasks.Task<DatabaseManager.ServiceReference2.AnalogInput[]> LoadDataToGridAIAsync() {
            return base.Channel.LoadDataToGridAIAsync();
        }
        
        public DatabaseManager.ServiceReference2.DigitalInput[] LoadDataToGridDI() {
            return base.Channel.LoadDataToGridDI();
        }
        
        public System.Threading.Tasks.Task<DatabaseManager.ServiceReference2.DigitalInput[]> LoadDataToGridDIAsync() {
            return base.Channel.LoadDataToGridDIAsync();
        }
        
        public void SaveChanges(DatabaseManager.ServiceReference2.AnalogOutput AO, double change) {
            base.Channel.SaveChanges(AO, change);
        }
        
        public System.Threading.Tasks.Task SaveChangesAsync(DatabaseManager.ServiceReference2.AnalogOutput AO, double change) {
            return base.Channel.SaveChangesAsync(AO, change);
        }
        
        public void SaveChangesDO(DatabaseManager.ServiceReference2.DigitalOutput DO, double change) {
            base.Channel.SaveChangesDO(DO, change);
        }
        
        public System.Threading.Tasks.Task SaveChangesDOAsync(DatabaseManager.ServiceReference2.DigitalOutput DO, double change) {
            return base.Channel.SaveChangesDOAsync(DO, change);
        }
        
        public void SaveChangesAI(DatabaseManager.ServiceReference2.AnalogInput AI, bool change) {
            base.Channel.SaveChangesAI(AI, change);
        }
        
        public System.Threading.Tasks.Task SaveChangesAIAsync(DatabaseManager.ServiceReference2.AnalogInput AI, bool change) {
            return base.Channel.SaveChangesAIAsync(AI, change);
        }
        
        public void SaveChangesDI(DatabaseManager.ServiceReference2.DigitalInput DI, bool change) {
            base.Channel.SaveChangesDI(DI, change);
        }
        
        public System.Threading.Tasks.Task SaveChangesDIAsync(DatabaseManager.ServiceReference2.DigitalInput DI, bool change) {
            return base.Channel.SaveChangesDIAsync(DI, change);
        }
        
        public void Simulation(DatabaseManager.ServiceReference2.DigitalInput DI) {
            base.Channel.Simulation(DI);
        }
        
        public System.Threading.Tasks.Task SimulationAsync(DatabaseManager.ServiceReference2.DigitalInput DI) {
            return base.Channel.SimulationAsync(DI);
        }
        
        public void Simulation1(DatabaseManager.ServiceReference2.AnalogInput AI) {
            base.Channel.Simulation1(AI);
        }
        
        public System.Threading.Tasks.Task Simulation1Async(DatabaseManager.ServiceReference2.AnalogInput AI) {
            return base.Channel.Simulation1Async(AI);
        }
        
        public void LoadThreadDi() {
            base.Channel.LoadThreadDi();
        }
        
        public System.Threading.Tasks.Task LoadThreadDiAsync() {
            return base.Channel.LoadThreadDiAsync();
        }
        
        public void LoadThreadAi() {
            base.Channel.LoadThreadAi();
        }
        
        public System.Threading.Tasks.Task LoadThreadAiAsync() {
            return base.Channel.LoadThreadAiAsync();
        }
        
        public void startPLC() {
            base.Channel.startPLC();
        }
        
        public System.Threading.Tasks.Task startPLCAsync() {
            return base.Channel.startPLCAsync();
        }
        
        public System.Collections.Generic.Dictionary<string, bool> loadAdressAI(System.Collections.Generic.Dictionary<string, bool> AI) {
            return base.Channel.loadAdressAI(AI);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<string, bool>> loadAdressAIAsync(System.Collections.Generic.Dictionary<string, bool> AI) {
            return base.Channel.loadAdressAIAsync(AI);
        }
        
        public System.Collections.Generic.Dictionary<string, bool> loadAdressDI(System.Collections.Generic.Dictionary<string, bool> DI) {
            return base.Channel.loadAdressDI(DI);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<string, bool>> loadAdressDIAsync(System.Collections.Generic.Dictionary<string, bool> DI) {
            return base.Channel.loadAdressDIAsync(DI);
        }
        
        public System.Collections.Generic.Dictionary<string, bool> loadAdressAO(System.Collections.Generic.Dictionary<string, bool> AO) {
            return base.Channel.loadAdressAO(AO);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<string, bool>> loadAdressAOAsync(System.Collections.Generic.Dictionary<string, bool> AO) {
            return base.Channel.loadAdressAOAsync(AO);
        }
        
        public System.Collections.Generic.Dictionary<string, bool> loadAdressDO(System.Collections.Generic.Dictionary<string, bool> DO) {
            return base.Channel.loadAdressDO(DO);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<string, bool>> loadAdressDOAsync(System.Collections.Generic.Dictionary<string, bool> DO) {
            return base.Channel.loadAdressDOAsync(DO);
        }
        
        public void clearData() {
            base.Channel.clearData();
        }
        
        public System.Threading.Tasks.Task clearDataAsync() {
            return base.Channel.clearDataAsync();
        }
        
        public void WriteXML() {
            base.Channel.WriteXML();
        }
        
        public System.Threading.Tasks.Task WriteXMLAsync() {
            return base.Channel.WriteXMLAsync();
        }
        
        public void ReadXML() {
            base.Channel.ReadXML();
        }
        
        public System.Threading.Tasks.Task ReadXMLAsync() {
            return base.Channel.ReadXMLAsync();
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference2.ITrending", CallbackContract=typeof(DatabaseManager.ServiceReference2.ITrendingCallback))]
    public interface ITrending {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITrending/SubscriberInitialization", ReplyAction="http://tempuri.org/ITrending/SubscriberInitializationResponse")]
        void SubscriberInitialization();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITrending/SubscriberInitialization", ReplyAction="http://tempuri.org/ITrending/SubscriberInitializationResponse")]
        System.Threading.Tasks.Task SubscriberInitializationAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITrendingCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ITrending/OnValueReceived")]
        void OnValueReceived(DatabaseManager.ServiceReference2.AnalogInput AI);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ITrending/OnValueReceived1")]
        void OnValueReceived1(DatabaseManager.ServiceReference2.DigitalInput DI);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ITrending/OnRemoveDI")]
        void OnRemoveDI(DatabaseManager.ServiceReference2.DigitalInput DI);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ITrending/OnRemoveAI")]
        void OnRemoveAI(DatabaseManager.ServiceReference2.AnalogInput AI);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ITrending/OnClearAI")]
        void OnClearAI();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ITrending/OnClearDI")]
        void OnClearDI();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITrendingChannel : DatabaseManager.ServiceReference2.ITrending, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TrendingClient : System.ServiceModel.DuplexClientBase<DatabaseManager.ServiceReference2.ITrending>, DatabaseManager.ServiceReference2.ITrending {
        
        public TrendingClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public TrendingClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public TrendingClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public TrendingClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public TrendingClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public void SubscriberInitialization() {
            base.Channel.SubscriberInitialization();
        }
        
        public System.Threading.Tasks.Task SubscriberInitializationAsync() {
            return base.Channel.SubscriberInitializationAsync();
        }
    }
}
