//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealTimeDriver.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IRealTimeDriver")]
    public interface IRealTimeDriver {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRealTimeDriver/SendMessage", ReplyAction="http://tempuri.org/IRealTimeDriver/SendMessageResponse")]
        void SendMessage(double number, string address);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRealTimeDriver/SendMessage", ReplyAction="http://tempuri.org/IRealTimeDriver/SendMessageResponse")]
        System.Threading.Tasks.Task SendMessageAsync(double number, string address);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRealTimeDriverChannel : RealTimeDriver.ServiceReference1.IRealTimeDriver, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RealTimeDriverClient : System.ServiceModel.ClientBase<RealTimeDriver.ServiceReference1.IRealTimeDriver>, RealTimeDriver.ServiceReference1.IRealTimeDriver {
        
        public RealTimeDriverClient() {
        }
        
        public RealTimeDriverClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RealTimeDriverClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RealTimeDriverClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RealTimeDriverClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void SendMessage(double number, string address) {
            base.Channel.SendMessage(number, address);
        }
        
        public System.Threading.Tasks.Task SendMessageAsync(double number, string address) {
            return base.Channel.SendMessageAsync(number, address);
        }
    }
}
