//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportManager.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IReportManager")]
    public interface IReportManager {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReportManager/Report1", ReplyAction="http://tempuri.org/IReportManager/Report1Response")]
        void Report1(double time);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReportManager/Report1", ReplyAction="http://tempuri.org/IReportManager/Report1Response")]
        System.Threading.Tasks.Task Report1Async(double time);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReportManager/Report2", ReplyAction="http://tempuri.org/IReportManager/Report2Response")]
        void Report2(string priority);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReportManager/Report2", ReplyAction="http://tempuri.org/IReportManager/Report2Response")]
        System.Threading.Tasks.Task Report2Async(string priority);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReportManager/Report3", ReplyAction="http://tempuri.org/IReportManager/Report3Response")]
        void Report3(string tag, double time);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReportManager/Report3", ReplyAction="http://tempuri.org/IReportManager/Report3Response")]
        System.Threading.Tasks.Task Report3Async(string tag, double time);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReportManager/Report4", ReplyAction="http://tempuri.org/IReportManager/Report4Response")]
        void Report4();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReportManager/Report4", ReplyAction="http://tempuri.org/IReportManager/Report4Response")]
        System.Threading.Tasks.Task Report4Async();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReportManager/Report5", ReplyAction="http://tempuri.org/IReportManager/Report5Response")]
        void Report5();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReportManager/Report5", ReplyAction="http://tempuri.org/IReportManager/Report5Response")]
        System.Threading.Tasks.Task Report5Async();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReportManager/Report6", ReplyAction="http://tempuri.org/IReportManager/Report6Response")]
        void Report6(string tagName, string tag);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReportManager/Report6", ReplyAction="http://tempuri.org/IReportManager/Report6Response")]
        System.Threading.Tasks.Task Report6Async(string tagName, string tag);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IReportManagerChannel : ReportManager.ServiceReference1.IReportManager, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ReportManagerClient : System.ServiceModel.ClientBase<ReportManager.ServiceReference1.IReportManager>, ReportManager.ServiceReference1.IReportManager {
        
        public ReportManagerClient() {
        }
        
        public ReportManagerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ReportManagerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReportManagerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReportManagerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void Report1(double time) {
            base.Channel.Report1(time);
        }
        
        public System.Threading.Tasks.Task Report1Async(double time) {
            return base.Channel.Report1Async(time);
        }
        
        public void Report2(string priority) {
            base.Channel.Report2(priority);
        }
        
        public System.Threading.Tasks.Task Report2Async(string priority) {
            return base.Channel.Report2Async(priority);
        }
        
        public void Report3(string tag, double time) {
            base.Channel.Report3(tag, time);
        }
        
        public System.Threading.Tasks.Task Report3Async(string tag, double time) {
            return base.Channel.Report3Async(tag, time);
        }
        
        public void Report4() {
            base.Channel.Report4();
        }
        
        public System.Threading.Tasks.Task Report4Async() {
            return base.Channel.Report4Async();
        }
        
        public void Report5() {
            base.Channel.Report5();
        }
        
        public System.Threading.Tasks.Task Report5Async() {
            return base.Channel.Report5Async();
        }
        
        public void Report6(string tagName, string tag) {
            base.Channel.Report6(tagName, tag);
        }
        
        public System.Threading.Tasks.Task Report6Async(string tagName, string tag) {
            return base.Channel.Report6Async(tagName, tag);
        }
    }
}
